apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-hostpath0
            - mountPath: /docker-entrypoint-initdb.d/
              name: mysql-hostpath1
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/mrniu/Desktop/ospp-docker-niu/OSPP-piflow-docker/mysql/db
          name: mysql-hostpath0
        - hostPath:
            path: /Users/mrniu/Desktop/ospp-docker-niu/OSPP-piflow-docker/mysql/init
          name: mysql-hostpath1
status: {}
