apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: piflow-serve
  name: piflow-serve
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: piflow-serve
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: piflow-serve
    spec:
      containers:
        - image: piflow-serve
          name: piflow-server
          ports:
            - containerPort: 8002
          resources: {}
          volumeMounts:
            - mountPath: /opt/spark
              name: spark
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/mrniu/Desktop/ospp-docker-niu/OSPP-piflow-docker
          name: spark
status: {}
